sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 286009
  wechat:
    appid: wx78360a1b42fe4a43
    secret: 58f8823571fcbbefad6ba67d5fe2e0fb
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com

    bucket-name: java-kim

  redis:
    host: localhost
    port: 6379
    database: 10
